# Generated by Django 4.2.6 on 2023-11-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0002_remove_postmedia_post_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='media_file.post'),
        ),
    ]
