# Generated by Django 4.2.6 on 2023-11-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0003_remove_post_media_postmedia_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_file.post'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='stickers',
            field=models.FileField(blank=True, null=True, upload_to='media/stickers/'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
