# Generated by Django 4.2.6 on 2023-11-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0004_alter_post_title_alter_postmedia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='stickers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
