# Generated by Django 4.2.6 on 2023-11-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0006_post_user_postmedia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='user',
        ),
    ]
