# Generated by Django 4.2.6 on 2023-11-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0007_remove_postmedia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
