# Generated by Django 4.2.6 on 2023-11-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0009_alter_postmedia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_subpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='subpost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpost_media_files', to='media_file.post'),
        ),
    ]
