# Generated by Django 4.2.6 on 2023-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_file', '0014_sharepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='share_comment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='share_reaction',
            field=models.CharField(choices=[('like', 'Like'), ('haha', 'Haha')], default=None, max_length=20, null=True),
        ),
    ]
