# Generated by Django 4.2.6 on 2023-11-08 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_file', '0016_userfriends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriends',
            name='cancel_request',
            field=models.ManyToManyField(null=True, related_name='cancel_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriends',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriends',
            name='requested_by',
            field=models.ManyToManyField(null=True, related_name='friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
