# Generated by Django 4.2.6 on 2023-10-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='education',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='portfolio_educations', to='test_app.education'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, related_name='portfolio_work_experiences', to='test_app.workexperience'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='portfolio_hobbies', to='test_app.hobby'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='portfolio_skills', to='test_app.skill'),
        ),
    ]
